filename: "mock_{{.InterfaceName}}.go"
dir: "resources/mocks/{{.InterfaceDirRelative}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
all: True
disable-version-string: True
with-expecter: True
packages:
    github.com/arielsrv/go-metric/metrics:
        config:
            recursive: True
log-level: Warn
