// Code generated by mockery. DO NOT EDIT.

package metrics

import (
	metrics "github.com/arielsrv/go-metric/metrics"
	mock "github.com/stretchr/testify/mock"
)

// MockCollectorFactory is an autogenerated mock type for the CollectorFactory type
type MockCollectorFactory struct {
	mock.Mock
}

type MockCollectorFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectorFactory) EXPECT() *MockCollectorFactory_Expecter {
	return &MockCollectorFactory_Expecter{mock: &_m.Mock}
}

// Prometheus provides a mock function with given fields:
func (_m *MockCollectorFactory) Prometheus() metrics.Metrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Prometheus")
	}

	var r0 metrics.Metrics
	if rf, ok := ret.Get(0).(func() metrics.Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Metrics)
		}
	}

	return r0
}

// MockCollectorFactory_Prometheus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prometheus'
type MockCollectorFactory_Prometheus_Call struct {
	*mock.Call
}

// Prometheus is a helper method to define mock.On call
func (_e *MockCollectorFactory_Expecter) Prometheus() *MockCollectorFactory_Prometheus_Call {
	return &MockCollectorFactory_Prometheus_Call{Call: _e.mock.On("Prometheus")}
}

func (_c *MockCollectorFactory_Prometheus_Call) Run(run func()) *MockCollectorFactory_Prometheus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectorFactory_Prometheus_Call) Return(_a0 metrics.Metrics) *MockCollectorFactory_Prometheus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCollectorFactory_Prometheus_Call) RunAndReturn(run func() metrics.Metrics) *MockCollectorFactory_Prometheus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollectorFactory creates a new instance of MockCollectorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectorFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectorFactory {
	mock := &MockCollectorFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
